In [91]:
#importing pandas
import pandas as pd

In [92]:
#Importing data sets and showing the first 5 rows of the data set
products_df = pd.read_csv(r'C:\Users\HMstore\OneDrive\Desktop\EDA project\Products.csv')
products_df.head()

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
0,1,AR-5381,NaN,NaN,NaN,Adjustable Race,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-07-01,NaN,Current
1,2,BA-8327,NaN,NaN,NaN,Bearing Ball,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-07-01,NaN,Current
2,3,BE-2349,NaN,NaN,NaN,BB Ball Bearing,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-07-01,NaN,Current
3,4,BE-2908,NaN,NaN,NaN,Headset Ball Bearings,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-07-01,NaN,Current
4,5,BL-2036,NaN,NaN,NaN,Blade,NaN,NaN,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003-07-01,NaN,Current

In [93]:
internet_sales_df = pd.read_excel(r'C:\Users\HMstore\OneDrive\Desktop\EDA project\InternetSales.xlsx')
internet_sales_df.head()

,ProductKey,OrderDate,ShipDate,CustomerKey,PromotionKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,RevisionNumber,OrderQuantity,...,UnitPriceDiscountPct,DiscountAmount,ProductStandardCost,TotalProductCost,29,6,98,19,36,100
0,310,2010-12-29,2011-01-05,21768,1,6,SO43697,1,1,1,...,0,0,2171.2942,2171.2942,NaN,NaN,NaN,3578.27,NaN,NaN
1,346,2010-12-29,2011-01-05,28389,1,7,SO43698,1,1,1,...,0,0,1912.1544,1912.1544,NaN,NaN,NaN,NaN,NaN,NaN
2,346,2010-12-29,2011-01-05,25863,1,1,SO43699,1,1,1,...,0,0,1912.1544,1912.1544,NaN,NaN,NaN,NaN,NaN,3399.9900
3,336,2010-12-29,2011-01-05,14501,1,4,SO43700,1,1,1,...,0,0,413.1463,413.1463,NaN,NaN,NaN,NaN,NaN,699.0982
4,346,2010-12-29,2011-01-05,11003,1,9,SO43701,1,1,1,...,0,0,1912.1544,1912.1544,NaN,3399.99,NaN,NaN,NaN,NaN

In [94]:
customers_df = pd.read_json(r'C:\Users\HMstore\OneDrive\Desktop\EDA project\customers.json')
customers_df.head()

,CustomerKey,GeographyKey,CustomerAlternateKey,Title,FirstName,MiddleName,LastName,NameStyle,BirthDate,MaritalStatus,...,EnglishOccupation,SpanishOccupation,FrenchOccupation,HouseOwnerFlag,NumberCarsOwned,AddressLine1,AddressLine2,Phone,DateFirstPurchase,CommuteDistance
0,12725,171,AW00012725,None,Gabrielle,None,James,0,1916-02-10,M,...,Manual,Obrero,Ouvrier,0,2,Nonnendamm 6500,None,1 (11) 500 555-0125,2013-08-18,1-2 Miles
1,16455,208,AW00016455,None,Deb,A,Moreno,0,1917-02-09,M,...,Manual,Obrero,Ouvrier,0,2,"99, rue du Départ",None,1 (11) 500 555-0144,2013-03-27,0-1 Miles
2,14841,171,AW00014841,None,Franklin,None,Pal,0,1917-06-05,M,...,Manual,Obrero,Ouvrier,1,1,Wertheimer Straße 8,None,1 (11) 500 555-0185,2013-09-02,1-2 Miles
3,18034,160,AW00018034,None,Ethan,J,Robinson,0,1917-09-20,M,...,Manual,Obrero,Ouvrier,0,2,Celler Weg 5,None,1 (11) 500 555-0160,2013-05-21,0-1 Miles
4,14992,228,AW00014992,None,Dale,B,Andersen,0,1918-02-11,M,...,Manual,Obrero,Ouvrier,1,1,2844 Plymouth Drive,None,1 (11) 500 555-0182,2013-09-04,5-10 Miles

In [95]:
sales_territory_df = pd.read_parquet(r'C:\Users\HMstore\OneDrive\Desktop\EDA project\SalesTerritory.parquet')
sales_territory_df.head()

,SalesTerritoryKey,SalesTerritoryAlternateKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup
0,1,1,Northwest,United States,North America
1,2,2,Northeast,United States,North America
2,3,3,Central,United States,North America
3,4,4,Southwest,United States,North America
4,5,5,Southeast,United States,North America

In [96]:
#inspecting the data sets
#====internet_sales_df======:
internet_sales_df.shape

(60398, 22)

In [97]:
internet_sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60398 entries, 0 to 60397
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ProductKey            60398 non-null  int64
 1   OrderDate             60398 non-null  datetime64[ns]
 2   ShipDate              60398 non-null  datetime64[ns]
 3   CustomerKey           60398 non-null  int64
 4   PromotionKey          60398 non-null  int64
 5   SalesTerritoryKey     60398 non-null  int64
 6   SalesOrderNumber      60398 non-null  object
 7   SalesOrderLineNumber  60398 non-null  int64
 8   RevisionNumber        60398 non-null  int64
 9   OrderQuantity         60398 non-null  int64
 10  UnitPrice             60398 non-null  float64
 11  ExtendedAmount        60398 non-null  float64
 12  UnitPriceDiscountPct  60398 non-null  int64
 13  DiscountAmount        60398 non-null  int64
 14  ProductStandardCost   60398 non-null  float64
 15  TotalProductCost      60398 non-null  float64
 16  29                    76 non-null     float64
 17  6                     12988 non-null  float64
 18  98                    6740 non-null   float64
 19  19                    7135 non-null   float64
 20  36                    0 non-null      float64
 21  100                   33400 non-null  float64
dtypes: datetime64[ns](2), float64(10), int64(9), object(1)
memory usage: 10.1+ MB

In [98]:
#melting the internet_sales dataframe:
copy = pd.melt(internet_sales_df, id_vars=[
    'OrderDate',
    'ShipDate',
    'CustomerKey',
    'PromotionKey',
    'SalesTerritoryKey',
    'SalesOrderNumber',
    'SalesOrderLineNumber',
    'RevisionNumber',
    'OrderQuantity',
    'UnitPrice',
    'ExtendedAmount',
    'UnitPriceDiscountPct',
    'DiscountAmount',
    'ProductStandardCost',
    'TotalProductCost'
], var_name="CurrencyKey", value_vars=[6,19,29,36,98,100], value_name="SalesAmount")

In [99]:
copy['CurrencyKey'].value_counts(dropna=False)

CurrencyKey
6      60398
19     60398
29     60398
36     60398
98     60398
100    60398
Name: count, dtype: int64

In [ ]:
#mapping the currency key to the currency name
currency_map = {
    6: "AUD",
    19: "CAD",
    29: "DEM",
    36: "EUR",
    98: "GBP",
    100: "USD"
}
copy['CurrencyKey'] = copy['CurrencyKey'].map(currency_map)
print(copy['CurrencyKey'].value_counts(dropna=False))

CurrencyKey
AUD    60398
CAD    60398
DEM    60398
EUR    60398
GBP    60398
USD    60398
Name: count, dtype: int64